{% set version = "0.9.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrix.utils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Matrix.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Matrix.utils/Matrix.utils_{{ version }}.tar.gz
  sha256: ebc59d3ef751775515586ff1f2396e429a1e9d91a10099d804134fcf74c0ae28

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-grr
  run:
    - r-base
    - r-matrix
    - r-grr

test:
  commands:
    - $R -e "library('Matrix.utils')"           # [not win]
    - "\"%R%\" -e \"library('Matrix.utils')\""  # [win]

about:
  home: https://github.com/cvarrichio/Matrix.utils
  license: GPL-3
  summary: Implements data manipulation methods such as cast, aggregate, and merge/join for Matrix and matrix-like objects.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - roryk

# Package: Matrix.utils
# Title: Data.frame-Like Operations on Sparse and Dense Matrix Objects
# Version: 0.9.7
# Author: Craig Varrichio <canthony427@gmail.com>
# Maintainer: Craig Varrichio <canthony427@gmail.com>
# Description: Implements data manipulation methods such as cast, aggregate, and merge/join for Matrix and matrix-like objects.
# Depends: R (>= 3.0.0), Matrix
# Imports: grr, methods, stats
# Suggests: testthat
# License: GPL-3
# URL: https://github.com/cvarrichio/Matrix.utils
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-04-19 15:25:08 UTC; Craig_Varrichio
# Repository: CRAN
# Date/Publication: 2018-04-19 22:04:49 UTC
