travis:
  secure:
    BINSTAR_TOKEN: EqSLc2hrLYBqIw8xfdUT2BEjqgjNofDG+LopHPyzohfSf6YbiWvgu7eCIXmb/tcmQlv0AMr2UaeLnWBNEDJkYY2tfToWm4S5vBUeBOO034W4z9go5jhApWleenI/dkMD7nvzFEliSLY3hC6f2IsCzPDa121+aWeNtDq3puMM7qgbKsy7DfdFV2ouiFy+JeFVOav2hMrZyvVS2WwJglc8Z+SBpBWJzIkQjP30MPMf18StKmZ/YJ2JFByc47+ybGHKzkNBgmwSX1s9NpK58H6+tn57itwT3Oy3Q23lBfZ8oXyIF1aYyisuDsMsB+27BqZpcmqF3nKdzsICTOHWiBs3wL1zlz9+7JSN8DkXm+csM5j28kggGCZ0+U5phBCq2m5FwfFriXhnzaP155zq+1ypCVGJeDUNYmx4RxUh3c2sDY/Ct21XWTIH+buZm/dTYrhU9ypQExY+e/BIilVmzSRuBqYOtla7ms+t8r+qHB0gsUZk6+5xRI2cg0QH2eKBlxkTASRwAwkzqOxwJ1dt5+QVtIR7/baHUaVZXkeYcKNP3jc9ARe56FQT6DngbvdSjTAobG1XpRlVnuShsu7BjFVsWywbPCeLmYtcGW7Rm4WyxjA/CJnxK9bpZ6qLQx5/kqwPyVdi2FcsMEKeXhVBMtMC5TOonZIU9954EbuMehlTjbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
